### ISSUE TITLE
TypeError: pidusage.stat is not a function

### ISSUE THREAD

**Issue by filipesilva** [soyuka/pidusage-tree#6]
Heya, I tried using this package today and got the following error:

```
TypeError: pidusage.stat is not a function
        at D:\work\cli\node_modules\pidusage-tree\index.js:13:16
        at D:\work\cli\node_modules\pidtree\lib\tree.js:65:14
        at D:\work\cli\node_modules\pidtree\lib\wmic.js:70:5
        at ChildProcess.<anonymous> (D:\work\cli\node_modules\pidtree\lib\bin.js:44:5)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Looking at https://github.com/soyuka/pidusage#usage, it seems that the call should be `pidusage(pids, function (err, stats) {` instead of `pidusage.stat(pids, function (err, stats) {` (dropping the `.stats` method.

**Comment by soyuka** [comment]
thanks!
